baseurl = "https://reinierdevries.nl/"
title = "Reinier de Vries"
languageCode = "en-us"
theme = "hello-friend-ng"
pagination.pagerSize = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "How to center a div?"

  disableReadOtherPosts = false
  enableSharingButtons = true
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Reinier de Vries"
  keywords = "homepage"
  images = [""]

  [[params.social]]
    name = "github"
    url  = "https://github.com/reintjuu/"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/reinierdevries/"

  [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/reinier-de-vries/"

[taxonomies]
  category = "blog"
  tag = "tags"
  series = "series"

[languages]
  [languages.en]
    title = "Reinier de Vries"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params.logo]
    logoText = "Reinier de Vries"
    logoHomeLink = "/"
